CREATE EXTENSION postgis;
-- enterprise definition
-- DROP TABLE enterprise;
CREATE TABLE enterprise ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, city varchar(255) NULL, "name" varchar(255) NULL, time_zone varchar(255) NULL, CONSTRAINT enterprise_pkey PRIMARY KEY (id));

-- manager definition
-- DROP TABLE manager;
CREATE TABLE manager ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "password" varchar(255) NOT NULL, username varchar(255) NOT NULL, CONSTRAINT manager_pkey PRIMARY KEY (id), CONSTRAINT uk2hgi0rwp93mv70sjq1kkuhy18 UNIQUE (username));

-- vehicle_model definition
-- DROP TABLE vehicle_model;
CREATE TABLE vehicle_model ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, brand_name varchar(255) NOT NULL, fuel_tank_capacity int4 NULL, load_capacity int4 NULL, model_name varchar(255) NOT NULL, seats_number int4 NULL, "type" varchar(255) NOT NULL, CONSTRAINT vehicle_model_pkey PRIMARY KEY (id), CONSTRAINT vehicle_model_type_check CHECK (((type)::text = ANY ((ARRAY['PASSENGER'::character varying, 'TRUCK'::character varying, 'BUS'::character varying])::text[]))));

-- driver definition
-- DROP TABLE driver;
CREATE TABLE driver ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "name" varchar(255) NULL, salary float8 NULL, enterprise_id int8 NOT NULL, CONSTRAINT driver_pkey PRIMARY KEY (id), CONSTRAINT fkkn32vhumwfy20tb1nyoedu0cc FOREIGN KEY (enterprise_id) REFERENCES enterprise(id));

-- manager_enterprise definition
-- DROP TABLE manager_enterprise;
CREATE TABLE manager_enterprise ( manager_id int8 NOT NULL, enterprise_id int8 NOT NULL, CONSTRAINT manager_enterprise_pkey PRIMARY KEY (manager_id, enterprise_id), CONSTRAINT fko68o8whf1ki86657ejfwtcsuq FOREIGN KEY (manager_id) REFERENCES manager(id), CONSTRAINT fkr9ut78jg6qe0xffpp80i2leip FOREIGN KEY (enterprise_id) REFERENCES enterprise(id));

-- vehicle definition
-- DROP TABLE vehicle;
CREATE TABLE vehicle ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, color varchar(255) NOT NULL, license_plate_number varchar(255) NOT NULL, mileage int4 NOT NULL, production_year int4 NOT NULL, purchase_date_time timestamp(6) NOT NULL, purchase_price int4 NOT NULL, active_driver_id int8 NULL, enterprise_id int8 NOT NULL, vehicle_model_id int8 NOT NULL, CONSTRAINT ukdcqe8hg5fn9n3qe0xtjtuc22q UNIQUE (active_driver_id), CONSTRAINT ukl0rexg57v3gro2g6x11x2tcap UNIQUE (license_plate_number), CONSTRAINT vehicle_mileage_check CHECK ((mileage >= 0)), CONSTRAINT vehicle_pkey PRIMARY KEY (id), CONSTRAINT vehicle_production_year_check CHECK ((production_year >= 1885)), CONSTRAINT vehicle_purchase_price_check CHECK ((purchase_price >= 0)), CONSTRAINT fk54qrkgsxrib4y2owq5nw66x4n FOREIGN KEY (active_driver_id) REFERENCES driver(id), CONSTRAINT fk8yj07js636mcyliis1jowdcm3 FOREIGN KEY (vehicle_model_id) REFERENCES vehicle_model(id), CONSTRAINT fkha1dpabmbk2v938vhsx1x9090 FOREIGN KEY (enterprise_id) REFERENCES enterprise(id));

-- driver_vehicle definition
-- DROP TABLE driver_vehicle;
CREATE TABLE driver_vehicle ( vehicle_id int8 NOT NULL, driver_id int8 NOT NULL, CONSTRAINT driver_vehicle_pkey PRIMARY KEY (vehicle_id, driver_id), CONSTRAINT fk8isv9i3mua4b32jtafc8rc0gn FOREIGN KEY (vehicle_id) REFERENCES vehicle(id), CONSTRAINT fkg99wbb85t2wabnw6j89her2gj FOREIGN KEY (driver_id) REFERENCES driver(id));

-- geo_point definition
-- DROP TABLE geo_point;
CREATE TABLE geo_point ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "position" geometry(point, 4326) NOT NULL, visited_at timestamp(6) NOT NULL, trip_id int8 NULL, vehicle_id int8 NULL, CONSTRAINT geo_point_pkey PRIMARY KEY (id));

-- trip definition
-- DROP TABLE trip;
CREATE TABLE trip ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, end_date timestamp(6) NULL, mileage int4 NOT NULL, start_date timestamp(6) NULL, end_geo_point_id int8 NULL, start_geo_point_id int8 NULL, vehicle_id int8 NOT NULL, CONSTRAINT trip_pkey PRIMARY KEY (id), CONSTRAINT ukajyp7vljj41jlwko03np5xobn UNIQUE (start_geo_point_id), CONSTRAINT ukh8ijp89s2jtwggyhdlnoxtxx4 UNIQUE (end_geo_point_id));

-- geo_point foreign keys
ALTER TABLE geo_point ADD CONSTRAINT fkf23veoaoadb26bpx716un5wf5 FOREIGN KEY (vehicle_id) REFERENCES vehicle(id);
ALTER TABLE geo_point ADD CONSTRAINT fkis235dv9rmudujqsm5up08jkm FOREIGN KEY (trip_id) REFERENCES trip(id) DEFERRABLE INITIALLY IMMEDIATE;

-- trip foreign keys
ALTER TABLE trip ADD CONSTRAINT fkbq1jue5o9b5fo0vbj258qcv3x FOREIGN KEY (start_geo_point_id) REFERENCES geo_point(id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE trip ADD CONSTRAINT fkft11qdu9g6igqi4060a2mltg FOREIGN KEY (end_geo_point_id) REFERENCES geo_point(id) DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE trip ADD CONSTRAINT fkjhbutn7n8cwbwv6kxvawfjy5 FOREIGN KEY (vehicle_id) REFERENCES vehicle(id);